name: Compile Kernel (Vio 2)

on:
  workflow_dispatch:
    inputs:
      clang_version:
        description: Type the clang version of ur kernel
        required: true
        type: choice
        options:
          - clang-3289846
          - clang-r450784e
          - clang-r475365b
          - clang-r487747c
          - clang-r498229b
          - clang-r510928
          - clang-r547379
          - clang-r563880
          - clang-r563880c
          - clang-r574158
          - clang-stable

      kernel_source:
        description: Kernel Source Repo URL
        required: true
        type: string

      kernel_branch:
        description: Kernel Branch
        required: true
        type: string

      defconfig_name:
        description: Defconfig Name
        required: true
        type: string

      device_codename:
        description: Device Codename (e.g. marble, alioth, vayu)
        required: true
        type: string

      ksu_type:
        description: "KernelSU Version"
        required: false
        type: choice
        options:
          - None
          - KernelSU-by-xx
          - ReSukiSU-with-susfs

      telegram_chat_id:
        description: "Telegram Chat ID (e.g. -1001234567890)"
        required: true
        type: string

      telegram_bot_token:
        description: "Telegram Bot Token (e.g. 123456:ABC-DEF...)"
        required: true
        type: string

jobs:
  Kernel_CI:
    env:
      GH_TOKEN: ${{ github.token }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
      checks: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup SWAP
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 16

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y bc bison flex libssl-dev libelf-dev libdw-dev build-essential lz4 git python3 curl dwarves cpio lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
          
      - name: Clone Kernel Source
        run: |
          git clone --depth=1 -b ${{ inputs.kernel_branch }} ${{ inputs.kernel_source }} kernel

      - name: Prepare Metadata
        run: |
          cd kernel
          echo "KERNEL_VER=$(make kernelversion)" >> $GITHUB_ENV
          echo "LAST_COMMIT=$(git log -1 --pretty=%s)" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "SUSFS_LABEL=$([[ "${{ inputs.ksu_type }}" == *"susfs"* ]] && echo "Yes" || echo "No")" >> $GITHUB_ENV

      - name: Send Build Start Message
        run: |
          TG_MSG="*=========================*%0A"
          TG_MSG+="*    J  U  S  T  U  S    *%0A"
          TG_MSG+="*       K E R N E L      *%0A"
          TG_MSG+="*========================*%0A"
          TG_MSG+="*Compiler*: \`${{ inputs.clang_version }}\`%0A"
          TG_MSG+="*Linux Version*: \`${KERNEL_VER}\`%0A"
          TG_MSG+="*Device*: \`${{ inputs.device_codename }}\`%0A"
          TG_MSG+="*KernelSU*: \`${{ inputs.ksu_type }}\`%0A"
          TG_MSG+="*SUSFS*: \`${SUSFS_LABEL}\`%0A"
          TG_MSG+="*Build Date*: \`$(date +'%Y-%m-%d %H:%M')\`%0A"
          TG_MSG+="*Last Commit*: \`${LAST_COMMIT}\`%0A"
          TG_MSG+="*Commit Hash*: \`${COMMIT_HASH}\`"
          curl -sX POST "https://api.telegram.org/bot${{ inputs.telegram_bot_token }}/sendMessage" \
            -d "chat_id=${{ inputs.telegram_chat_id }}" \
            -d "parse_mode=Markdown" \
            -d "disable_web_page_preview=true" \
            -d "text=${TG_MSG}"
            
      - name: Download AOSP Clang
        run: |
          mkdir -p toolchains/${{ inputs.clang_version }}
          cd toolchains
          OLD_TAGS=("clang-r450784e" "clang-r475365b" "clang-r487747c" "clang-r498229b" "clang-r510928")
          if [[ " ${OLD_TAGS[@]} " =~ " ${{ inputs.clang_version }} " ]]; then
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/tags/android-14.0.0_r33/${{ inputs.clang_version }}.tar.gz
          else
            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/${{ inputs.clang_version }}.tar.gz
          fi
          tar -xf "${{ inputs.clang_version }}.tar.gz" -C ${{ inputs.clang_version }}

      - name: Compile Kernel
        run: |
          CLANG_ROOT="${GITHUB_WORKSPACE}/toolchains/${{ inputs.clang_version }}/bin"
          export PATH="${CLANG_ROOT}:$PATH"
          export ARCH=arm64
          export SUBARCH=arm64
          export LLVM=1
          export LLVM_IAS=1
          export CC="${CLANG_ROOT}/clang"
          export CXX="${CLANG_ROOT}/clang++"
          export HOSTCC="${CLANG_ROOT}/clang"
          export HOSTCXX="${CLANG_ROOT}/clang++"
          export LD="${CLANG_ROOT}/ld.lld"
          export AR="${CLANG_ROOT}/llvm-ar"
          export NM="${CLANG_ROOT}/llvm-nm"
          export OBJCOPY="${CLANG_ROOT}/llvm-objcopy"
          export OBJDUMP="${CLANG_ROOT}/llvm-objdump"
          export STRIP="${CLANG_ROOT}/llvm-strip"
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          cd kernel
          case "${{ inputs.ksu_type }}" in
            "KernelSU-by-xx")
              curl -LSs "https://raw.githubusercontent.com/Justadeayo/KernelSU/refs/heads/master/kernel/setup.sh" | bash -s master
              ;;
            "ReSukiSU-with-susfs")
              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main
              ;;
          esac
          touch ./.scmversion
          if [[ "${{ inputs.ksu_type }}" != "None" ]]; then
            DEFCONFIG="arch/arm64/configs/${{ inputs.defconfig_name }}"
            echo "CONFIG_KSU=y" >> $DEFCONFIG
            echo "CONFIG_KPROBES=y" >> $DEFCONFIG
            echo "CONFIG_KPROBE_EVENTS=y" >> $DEFCONFIG
            echo "CONFIG_KSU_KPROBE_HOOKS=y" >> $DEFCONFIG
            echo "CONFIG_OVERLAY_FS=y" >> $DEFCONFIG
          fi
          if [[ "${{ inputs.ksu_type }}" == *"susfs"* ]]; then
            curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_4.14.patch
            curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh
            patch -p1 < susfs.patch
            bash inline.sh
            echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/${{ inputs.defconfig_name }}
          fi
          make O=out ${{ inputs.defconfig_name }}
          if [[ "${{ inputs.ksu_type }}" == "KernelSU-by-xx" ]]; then
            echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=y" >> out/.config
          fi
          make -j$(nproc) O=out 

      - name: Make AnyKernel3
        run: |
          ZIP_NAME="${{ inputs.device_codename }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          BOOT_DIR="kernel/out/arch/arm64/boot"
          git clone -b master https://github.com/Justadeayo/AnyKernel3.git
          if [ -f $BOOT_DIR/Image.gz ]; then cp $BOOT_DIR/Image.gz AnyKernel3/Image.gz
          elif [ -f $BOOT_DIR/Image.gz-dtb ]; then cp $BOOT_DIR/Image.gz-dtb AnyKernel3/Image.gz-dtb; fi
          if [ -f $BOOT_DIR/dtb.img ]; then cp $BOOT_DIR/dtb.img AnyKernel3/dtb
          elif [ -f $BOOT_DIR/dtb ]; then cp $BOOT_DIR/dtb AnyKernel3/dtb; fi
          if [ -f $BOOT_DIR/dtbo.img ]; then cp $BOOT_DIR/dtbo.img AnyKernel3/dtbo.img; fi
          cd AnyKernel3
          sed -i "s/device.name1=.*/device.name1=${{ inputs.device_codename }}/" anykernel.sh
          zip -r9 ../"${ZIP_NAME}.zip" * -x .git

      - name: Create GitHub Release
        run: |
          REL_NAME="${{ inputs.device_codename }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
          ZIP_FILE=$(ls *.zip)
          gh release create "$REL_NAME" --title "$REL_NAME" --notes "" "${ZIP_FILE}"

      - name: Upload to Telegram
        run: |
          ZIP_FILE=$(ls *.zip)
          SUCCESS_MSG="*Build Successful!* ✅%0A*Device*: \`${{ inputs.device_codename }}\`%0A*KernelSU*: \`${{ inputs.ksu_type }}\`%0A*SUSFS*: \`${SUSFS_LABEL}\`%0A*Date*: \`$(date -u +'%Y-%m-%d %H:%M UTC')\`"
          curl -sX POST -F document=@"${ZIP_FILE}" "https://api.telegram.org/bot${{ inputs.telegram_bot_token }}/sendDocument" -F "chat_id=${{ inputs.telegram_chat_id }}" -F "parse_mode=Markdown" -F "caption=${SUCCESS_MSG}"
